version: 1
formatters:
  brief:
    format: '[%(threadName)s] %(levelname)-7s [%(name)s] %(message)s'
  precise:
    format: '%(asctime)s [%(threadName)s] %(levelname)s [%(name)s.%(module)s] %(message)s'
    datefmt: '%d-%m-%Y %H:%M:%S'
handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: precise
    filename: ./logs/scraper_log.log
    maxBytes: 5242880
    backupCount: 3
    level: DEBUG
  console:
    class: logging.StreamHandler
    formatter: brief
    level: DEBUG
    stream: ext://sys.stdout
root:
  level: DEBUG
  handlers: [file, console]
loggers:
  scraper:
    level: DEBUG
    handlers: [file, console]
    propagate: no
  filter:
    level: DEBUG
    handlers: [file, console]
    propagate: no
